name: Clean TSV Files

on:
  workflow_dispatch:
  push:
    paths:
      - '**.tsv'

jobs:
  clean-tsvs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -la && echo && ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pandas
        run: pip install pandas

      - name: Clean all TSVs (repo root or data/)
        shell: python
        run: |
          from pathlib import Path
          import pandas as pd

          # config
          repo_root = Path(".").resolve()
          input_root = Path("data") if Path("data").exists() else Path(".")
          output_dir = Path("cleaned").resolve()
          required_cols = ["region-name", "full-name", "short-name"]
          alias_map = {
              "region": "region-name",
              "regionname": "region-name",
              "fullname": "full-name",
              "name": "full-name",
              "short": "short-name",
              "shortname": "short-name",
          }

          output_dir.mkdir(parents=True, exist_ok=True)
          processed = 0

          for tsv_file in sorted(input_root.rglob("*.tsv")):
              # skip files already in cleaned/
              if output_dir in tsv_file.resolve().parents:
                  continue

              print(f"cleaning: {tsv_file}")

              df = pd.read_csv(tsv_file, sep="\t", dtype=str).fillna("")

              # normalise headers
              df.columns = [c.strip().lower().replace(" ", "-").replace("_", "-") for c in df.columns]
              df = df.rename(columns=alias_map)

              # keep only known columns if present; otherwise keep all as-is
              have = [c for c in required_cols if c in df.columns]
              if have:
                  df = df[have]

              # strip whitespace in all cells
              df = df.applymap(lambda x: x.strip())

              # write to cleaned/<relative_path>
              rel = tsv_file.resolve().relative_to(repo_root)
              out_path = output_dir / rel
              out_path.parent.mkdir(parents=True, exist_ok=True)
              df.to_csv(out_path, sep="\t", index=False)
              print(f"wrote: {out_path}")
              processed += 1

          if processed == 0:
              raise SystemExit("no .tsv files found under data/ or repo root")
